[project]
name = "vectorllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "vectoreddd@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "requests>=2.34.2",
    "tqdm>=4.70.1",
]

[project.scripts]
vectorllm = "vectorllm:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
